name: Update holzliebe.at

on:
  push:
    branches: 
      - master
  repository_dispatch:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
         node-version: 18.x

    - name: Install libvips
      run: sudo apt-get update && sudo apt-get install -y libvips-dev

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: npm install

    - name: Cache build assets
      uses: actions/cache@v4
      with:
        path: .cache/caches/gatsby-transformer-sharp
        key: ${{ runner.OS }}-build-${{ hashFiles('src/images/**/*.*') }}

    - name: Build
      run: npm run build
      
    - name: List output files
      run: ls -la

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      env:
        LOCAL_DIR: public
        ARGS: --parallel=5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
